### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by faviouz** [ashleysommer/sanic-cors#1]
```
$ pip install -U sanic-cors
Collecting sanic-cors
  Could not find a version that satisfies the requirement sanic-cors (from versions: )
No matching distribution found for sanic-cors
```

**Comment by faviouz** [comment]
This will do for now

```
$ pip install git+git://github.com/ashleysommer/sanic-cors.git
```

**Comment by ashleysommer** [comment]
Thanks. I haven't published the initial version (v 0.1.0) to Pypi yet because I haven't tested if it is fully working with Sanic, or if it is fully feature-compatible with flask-cors . I did document that git-address `pip install` workaround somewhere, but I don't see where I put it. I should put it in the readme.

**Comment by d-helix** [comment]
Any update on the Pypi publish timeline? Thanks

**Comment by ashleysommer** [comment]
Good question. I am getting the impression there is sufficient demand for this, so I will try to put it up within the next 5 days.

**Comment by ashleysommer** [comment]
Update, I know I said 5 days in the previous message, but it is slightly delayed because I am retargeting the plugin to work on Sanic 0.4.0/0.4.1.

Sanic is still a bit of a moving target at the moment, so it is hard to keep up.
