### ISSUE TITLE
Sanic-Plugins-Framework (spf) ">=" dependency in older Sanic-Cors versions

### ISSUE THREAD

**Issue by csis0247** [ashleysommer/sanic-cors#35]
I've recently been getting "AssertionError: App must be running before you can run middleware!" errors upon every server request, and the most likely cause was that I recreated my environment and reinstalled the requirements.txt. 

    sanic==19.3.1
    sanic-cors==0.9.8
    sanic-compress==0.1.1

Since I fixed the version, there shouldn't be a problem, right?

When I checked another server under the same code base, I found out that the difference was, theirs were using Sanic-Plugins-Framework 0.7.0, while mine was 0.8.2, probably because in Sanic-Cors' dependencies, a `>=` was used despite recent (breaking) changes.

Here's roughly how I started my server, the only solution for me was to force spf to 0.7.0 manually, or comment out CORS... :

    from sanic import Sanic
    from sanic_cors import CORS, cross_origin
    from sanic_compress import Compress
    import asyncio

    app = Sanic(__name__)
    CORS(app, automatic_options=True)
    Compress(app)
    app.static('/favicon.ico', './public/favicon.ico', name='favicon')

    server = app.create_server(debug=debug, host=host, port=hostport, return_asyncio_server=True)
    loop = asyncio.get_event_loop()
    task = asyncio.ensure_future(server)
    loop.run_forever()

Outside this dependency issue, how shall I update my code if I were to update to a newer Sanic / Sanic-Cors version?

I tried:

    @app.listener('after_server_start')
    async def notify_server_started(app, loop):
        CORS(app, automatic_options=True)

The callback was never called, but that's another story.

**Comment by ashleysommer** [comment]
Hi @csis0247 
This is the same problem as reported here: https://github.com/ashleysommer/sanicpluginsframework/issues/12

It is due to your use of "app.create_server()" rather than "app.run()"

App.create_server() never triggers the `"after_server_start"` event because it doesn't actually start the server, you do that manually a couple of lines later.

Newer versions of Sanic-Plugins-Framwork rely on a listener on the "after_server_start" event (opposed to "before_server_start" previously) to activate the registered plugins. This change was introduced for compatibility with Sanic ASGS mode.

From what I can tell, if you really need to use `app.create_server()` in your application instead of `app.run()`, then you are meant to trigger the `"after_server_start"` event yourself  after the `ensure_future` call, but due to the way Sanic handles the registered events, that is not currently possible to do yourself.

To fix SPF and all SPF-based plugins affected by this bug, change your code to look like this:
```
from spf import SanicPluginsFramework
...

...
loop = asyncio.get_event_loop()
server = app.create_server(debug=debug, host=host, port=hostport, return_asyncio_server=True)
task = asyncio.ensure_future(server)
spf._on_server_start(app, loop)
loop.run_forever()
```

**Comment by ashleysommer** [comment]
>I tried:
>```
>@app.listener('after_server_start')
>async def notify_server_started(app, loop):
>    CORS(app, automatic_options=True)
>```
>The callback was never called, but that's another story.

Its actually the same story. Its never called because app.create_server() doesn't trigger "after_server_start" event.

But even if you did trigger that event, your solution there wouldn't work.
`CORS(app, automatic_options=True)`
is a shortcut for this:
```
spf = SanicPluginsFramework(app)
cors = spf.register_plugin(CORS, automatic_options=True)
```
And that doesn't work after the server has started because you cannot run spf.register_plugin after the server has started.

**Comment by ashleysommer** [comment]
@csis0247 I've created a post on the Sanic community forum about this issue.
https://community.sanicframework.org/t/triggering-after-server-start-event-when-running-asyncio-server/385
Feel free to join in.

**Comment by csis0247** [comment]
Thank you! I really should have searched within Github instead of only through Google...

**Comment by ashleysommer** [comment]
@csis0247 
Good news, a fix for this in Sanic Core has been accepted, and will be in the next release of Sanic:
huge-success/sanic#1676
