### ISSUE TITLE
upper bounds on requirements

### ISSUE THREAD

**Issue by TheKevJames** [ashleysommer/sanic-cors#42]
First off, thanks for building and maintaining this extension! It has been extremely helpful :)

Would it be possible to get some upper bounds maintained in the `requirements.txt` file? I know this library has had some compatibility issues with Sanic v19.12+ -- if [this line[(https://github.com/ashleysommer/sanic-cors/blob/master/requirements.txt#L2) could have been updated to read `sanic>=18.12.0,<19.12.0`, that would have made my life a bit easier :) Doing this for the spf dependency, as well, could solve the same potential issue there!

I just saw the release notes for v0.10.0.post1 -- I see the note about not being compatible with v19.12 has been removed. Does that mean v0.10.0.post1 is now fully compatible with Sanic v19.12.0? Having that explicit in the `sanic-cors` dependencies would be a great way to be clear about this.

Note: I realize neither Sanic is not semver and sanic-cors is pre-v1 and thus unstable, so normal semver pinning rules don't apply (eg. pinning to, say, `sanic>=19.0,<20.0` soesn't really make sense). Perhaps just pinning to known compatible/incompatible versions would be enough?

**Comment by ashleysommer** [comment]
Hi @TheKevJames 
Thanks for your interest in Sanic-CORS.

Please note the requirements.txt _was_ updated to add an upper bound on Sanic on Jan 8th, literally the same day I found out about the incompatibility with Sanic 19.12+, https://github.com/ashleysommer/sanic-cors/blob/78857f321415ba6f6bc93f9d74ed21c94f5cf9c6/requirements.txt
This was released as 0.9.9.post4 on PyPI.
Same was done on the corresponding SPF release, on the same day. If you were using the latest version of Sanic-CORS and SanicPluginsFramework from that day, you should've been fine, both specified "Sanic>=0.8.3,<=19.6.3".

The v0.10.0 release was the first version with Full Sanic 19.12+ support, that is mentioned in the v0.10.0 release notes, and the upgrade warning in the README file was updated to reflect that.

v0.10.0.post1 was a postfix release to address a different Sanic 19.12 problem around error handling, release only a few hours after v0.10.0.

Historically, Sanic-CORS has always tried to support as many Sanic releases as possible, with compatibility checks and workarounds written directly into the source code. With this Plugin being used in hundreds (or thousands?) of Sanic projects, it is not my place to dictate which version of Sanic you should use. For that reason, only the minimum version was normally specified in the requirements.txt file, and that minimum version is always at least 4 releases behind Sanic latest release. That argument is even stronger in the case of SanicPluginsFramework, because developers need to use it to create plugins to support every version of Sanic their user's may be on. So I am again deliberately leaving the Sanic-CORS v0.10.0 and SPF v0.9.0 line open-ended with no maximum Sanic version, at least until I know more about the Sanic 20.3 release at the end of March. I don't forsee any potential compatibility issues, at this stage.

Not all Plugins are updated in a timely fashion to support a new release of Sanic. For that reason, to avoid potential breakages I recommend users specify their own maximum Sanic version in the requirements of their app project.

**Comment by ashleysommer** [comment]
Addendum to the above:

I will be converting Sanic-Plugins-Framework, and my plugins including Sanic-CORS, Sanic-RestPlus, Sanic-Jinja2-SPF, sometime in the next month or two, to Poetry for project orchestration and dependency management and remove the requirements.txt file. Poetry specifies dependencies in the pyproject.toml file in a similar way to javascript packages use a project.json file. Poetry can also use npm-notation (with `^` and `~`) for dependency versions, so we can have more control over which versions for the dependency resolver to collect.

As you mentioned, neither Sanic-CORS, SanicPluginsFramework, nor Sanic itself uses semantic versioning, and are still considered pre-release software and subject to breaking. Sanic resolves that issue in a way by publishing LTS releases, that are releases which only receive security updates, and no features introduced or potentially breaking changes used. I am considering doing LTS forks of SanicPluginsFramework and Sanic-CORS, which have their Sanic dependency pinned at a corresponding Sanic LTS release. That would be a good solution for users who need that kind of stability.

**Comment by TheKevJames** [comment]
Gotcha, thank you, that's very helpful.

I think I was a bit confused by my own tooling here -- I use Renovate for dependency updates and saw the following on the v0.10.0 release:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/3341822/74889384-bd265700-5335-11ea-99ba-8c4e01e158d4.png">

The second line of the note (which I notice is not present in the release notes on this repo, checking now) confused me -- "A new version coming out soon will work with sanic v19.12." in the v0.10.0 release notes implied to me that v0.10.0 was _not_ compatible yet, so I was looking for a future release which was indeed compatible.

In that case -- sorry, entirely a false alarm!

I entirely agree that the pinning should be in the hands of users -- personally, I have both `sanic` and `sanic-cors` pinned and my CI system runs `pip check` after installing both to verify compatibility. I _thought_ that was giving false positives since I misread the v0.10.0 release notes, but it turns out everything you're doing here makes sense and the problem was PEBKAC.

Sorry again for the issue -- and thanks for the in-depth explanation, much appreciated!

**Comment by ashleysommer** [comment]
Hi @TheKevJames 
Thanks for the resolution on this.

Looks like your Renovate tooling might be taking the release notes from the Changelog?
https://github.com/ashleysommer/sanic-cors/blob/master/CHANGELOG.md

That text matches the v0.10.0b1 change notes in the changelog. That note even exists in the changelog (the wording has changed now, but it used to read like that), however is supposed to be contextually attached to the v0.9.9.post4 release below it, not release above it.
